#----------------------------------------------------------------------
# 作者 ：杨东
# 时间 ：2019.08.12
# 版权 ：重庆邮电大学自动化学院汽车电子工程中心智能车辆技术团队
# 说明 ：
#      LCM_TurnLight 转向灯命令  0x0:Not Active:0x1：
#                              TurnRight；0x2：TurnLeft;0x3:DoubleLight
#----------------------------------------------------------------------

#请求---------------------------------------------------------
##定义赋值枚举
uint8 TurnOff=0
uint8 TurnLeft=1
uint8 TurnRight=2

#
uint8 TurnLightEnable

---
#返回值-----------------------------------------------------------
##定义赋值枚举
bool res
#控制字段

