#---------------------------------------------------------------
# 作者 ：杨东
# 时间 ：2019.08.12
# 版权 ：重庆邮电大学自动化学院汽车电子工程中心智能车辆技术团队
# 说明 ：
#----------------------------------------------------------------

#请求---------------------------------------------------------
##定义赋值枚举
uint8 TurnOff=0
uint8 Close=1
uint8 Open=2
#
uint8 WindowEnable

---
#返回值-----------------------------------------------------------
##定义赋值枚举
bool res
#控制字段

