#---------------------------------------------------------------
# 作者 ：杨东
# 时间 ：2019.08.12
# 版权 ：重庆邮电大学自动化学院汽车电子工程中心智能车辆技术团队
# 说明 ：
#      BCM BCM_Wipers 雨刮控制
#         0：停
#         6：低速刮刷
#         7：高速刮刷
#----------------------------------------------------------------

#请求---------------------------------------------------------
##定义赋值枚举
uint8 TurnOff=0
uint8 LowSpeed=6
uint8 HighSpeed=7
#
uint8 WipersEnable   

---
#返回值-----------------------------------------------------------
##定义赋值枚举
bool res
#控制字段


