#----相机检测目标参数
uint16 obj_Width              ##  //前方目标宽度       
uint16 obj_Height            ##  //前方目标高度  
uint16 obj_Length           ##  //前方目标长度  
uint16 obj_HeadingAngle       ## //前方目标航向角  
uint8 obj_TTC                 ## //前方目标瞬时碰撞时间TTC 
uint8 obj_headwaytime        ## //前方目标车距时间HWT
uint16 obj_Dy               ##  //前方目标横向位置 
uint16 obj_Dx               ##  //前方目标纵向位置 
uint16 obj_Vx               ## //前方目标绝对纵向速度  
uint16 obj_Vy              ##  //前方目标绝对横向速度  
uint8 obj_Track_ID          ## //前方目标跟踪ID   
uint8 obj_Class             ## //前方目标类型       
