#---------------------------------------------------------------
# 作者 ：lsxing
# 时间 ：2020.12.12
# 版权 ：重庆邮电大学自动化学院汽车电子工程中心智能车辆技术团队
# 说明 ：描述道路基本属性的消息结构
#----------------------------------------------------------------   

float32 velocity     #期望车速

float32 road_width   #道路宽度

float32 aeb_front   #AEB范围
float32 aeb_back
float32 aeb_left
float32 aeb_right

float32 detect_front  #检测范围
float32 detect_back
float32 detect_left
float32 detect_right
