#---------------------------------------------------------------
# 作者 ：杨东
# 时间 ：2019.08.12
# 版权 ：重庆邮电大学自动化学院汽车电子工程中心智能车辆技术团队
# 说明 ：
#      BCM BCM_Door 门锁控制
#         0x0  APA_NO_CMD
#         0x1  APA_UNLOCK_CMD
#         0x2  APA_LOCK_CMD
#----------------------------------------------------------------

#请求------------------------------------------------------------
##定义赋值枚举
uint8 NO_CMD=0
uint8 UNLOCK_CMD=6
uint8 LOCK_CMD=7
#控制字段
uint8 DoorLOCK


---
#返回值-----------------------------------------------------------
##定义赋值枚举
bool res
#控制字段

