#---------------------------------------------------------------
# 作者 ：杨东
# 时间 ：2019.08.12
# 版权 ：重庆邮电大学自动化学院汽车电子工程中心智能车辆技术团队
# 说明 ：
#----------------------------------------------------------------

#请求---------------------------------------------------------
##定义赋值枚举
uint8 Enable=0
uint8 Diable=1
#
uint8 APA_EPBrequestValid
uint8 APA_EPBrequest

---
#返回值-----------------------------------------------------------
##定义赋值枚举
bool res
#控制字段

