#------------------------------
#异常报警服务
#------------------------------
uint8  source   #消息来源
uint8  code     #错误码
---
uint8   isLidarOK
uint8   isNaviOK
uint8   isCtrlOK
uint8   isXavierOK


#----------请按照如下注释进行赋值调用服务-----------------

#------获取状态--------
#source-->  0
# 
#无异常申报，但需要获取状态source赋值为0
#-------------------

#------lidar--------
#source-->  1
#code  -->  0x00: 正常 
#           0x01：(某某)雷达错误
#           0x02：(某某)雷达错误
#-------------------

#------navi--------
#source-->  2
#code  -->  0x00: 正常 
#           0x01：
#           0x02：
#-------------------

#------ctrl--------
#source-->  3
#code  -->  0x00: 正常 
#           0x01：
#           0x02：
#-------------------